# channel
TERMINAL = "terminal"
WECHAT = "wechat"
WECHAT_MP = "wechat_mp"
WECHAT_MP_SERVICE = "wechat_mp_service"
WECHAT_COM = "wechat_com"
QQ = "qq"
GMAIL = "gmail"
TELEGRAM = "telegram"
SLACK = "slack"
HTTP = "http"
DINGTALK = "dingtalk"
FEISHU = "feishu"
DISCORD = "discord"

# model
GPT_3 = "gpt-3"
GPT_3_5 = "gpt-3.5"
GPT_4 = "gpt-4"
BAIDU = "baidu"
BING = "bing"
BARD = "bard"